# Para orquestrar os micro-frontend e o backend

version: '3.9'

services:
  bff:
    build: ./bff
    ports:
      - "5000:5000"
    env_file:
      - ./bff/.env

  mf_drawer:
    build: ./mf_drawer
    ports:
      - "8088:8080"

  mf_videos:
    build: ./mf_videos
    ports:
      - "8088:8081"
